### ISSUE TITLE
PullRefreshExample的一点bug

### ISSUE THREAD

**Issue by zhengxuanyi** [mrarronz/react-native-blog-examples#1]
封装的上拉加载组件 RefreshListView 会默认刷新两次？请问您有注意到吗？

**Comment by mrarronz** [comment]
这个问题应该只是在列表第一次加载的时候出现吧，确实有这个问题，个人认为与列表组件的onEndReachedThreshold有关，改用ListView可能也有这个问题。你可以自己加上限制条件，使底部组件开始的时候不做刷新，避免重复调用刷新接口。

**Comment by mrarronz** [comment]
@zhengxuanyi  ListView、FlatList的onEndReached方法会多次调用应该是React Native的bug，看看这个issue[#6002](https://github.com/facebook/react-native/issues/6002)，很多人都提到了这个问题

**Comment by mrarronz** [comment]
如果后面有好的解决方法，我会更新代码

**Comment by zhengxuanyi** [comment]
谢谢！




谢谢
------------------ 原始邮件 ------------------
发件人: "Zzzzz..."<notifications@github.com>;
发送时间: 2018年3月14日(星期三) 下午4:45
收件人: "mrarronz/react-native-blog-examples"<react-native-blog-examples@noreply.github.com>;
抄送: "俄╮冷血不需要理由"<978357074@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [mrarronz/react-native-blog-examples] PullRefreshExample的一点bug (#1)




如果后面有好的解决方法，我会更新代码

**Comment by Sxiaobai** [comment]
视频上的进度条卡卡的  一拖动的时候会一卡一卡的  咋解决啊

**Comment by mrarronz** [comment]
@Sxiaobai 应该是更新currentTime时造成Slider控件重新渲染导致的，这个问题我也注意到了，会想办法加以改进
