### ISSUE TITLE
横竖屏监听器移除问题

### ISSUE THREAD

**Issue by zhaofengnian18** [mrarronz/react-native-blog-examples#2]
我只想在播放器页面监听横竖屏旋转，其他页面都锁定竖屏，在播放器页生命周期willunmount移除监听器并未生效，其他页面还是会根据旋转切换横竖屏，请问有好的解决办法么

**Comment by mrarronz** [comment]
播放视频界面是需要支持横竖旋转的，其它界面只支持竖屏。是这个意思吧

这个应该很容易解决的，用[react-native-orientation](https://github.com/yamill/react-native-orientation)强制屏幕旋转。

具体方法：
1、app第一个页面componentDidMount中设置Orientation.lockToPortrait()强制竖屏，其它竖屏页面就不需要再设置了
2、视频播放页面横竖旋转参考demo，我代码写的很详细了。
3、由于播放器页面需要横竖旋转，播放器的转屏操作打乱了原本的竖屏设置。这时在播放器界面返回上一级页面时，使用Orientation.lockToPortrait()将屏幕锁定为竖屏，如果是从播放器界面进入一个新的界面，在新的界面componentDidMount方法中同样设置Orientation.lockToPortrait()就行了。

**Comment by zhaofengnian18** [comment]
我就是采用的这个方法，并没有生效，我在返回的页面的didmount,willmount,和constructor里面都试过写    Orientation.lockToPortrait();但是依然会横竖旋转

**Comment by mrarronz** [comment]
返回到上个页面后，这个页面并不会重新加载，didmount,willmount,和constructor都不会重新执行，当然不生效了。你没理解我的意思，所谓返回时设置Orientation.lockToPortrait()不是在之前的页面的生命周期函数中去调用这个方法，而是在返回操作的同时就去做这件事。两种方式你可以试一下：
1、如果你用到了react-navigation导航，A页面进入B页面（播放页面）时，使用如下代码：
```
this.props.navigation.navigate('B页面', {callback: (shouldForcePortrait)=>{
                         // 如果shouldForcePortrait=true，强制竖屏
                     }});
```
在B页面执行返回操作时传递参数
```
this.props.navigation.state.params.callback(true);
this.props.navigation.goBack();
```
这是使用了react-navigation返回传参的方式，其它导航库可能也有类似的方法

2、使用事件通知的方式，即react native的DeviceEventEmitter
在A页面的didmount方法中监听事件
```
this.listener = DeviceEventEmitter.addListener('事件名称', () => {
      Orientation.lockToPortrait();
    })
```
同时在willUnmount中移除监听
```
this.listener.remove();
```
在B页面执行返回操作时就发出通知
```
DeviceEventEmitter.emit('事件名称');  // 两处事件名称保持一致
```

**Comment by zhaofengnian18** [comment]
十分感谢，完美解决

**Comment by mrarronz** [comment]
@zhaofengnian18 建议你用第二种方法，第一种react-navigation的goBack传参的方式有些问题
[Unable to goBack and setParams](https://github.com/react-navigation/react-navigation/issues/288)

**Comment by zhaofengnian18** [comment]
恩，谢谢提醒，不过我修改过了，你一开始没放在一个对象中

**Comment by mrarronz** [comment]
👍

**Comment by xupengkun** [comment]
hello  有没有遇到过类似的问题，就是我在Xcode中设置我的App禁止横屏显示，然后再去使用react-native-orientation的时候就无法让屏幕旋转了。
另外在android中 react-native-orientation 的监听屏幕旋转的事件并不能用，所以导致我很焦灼

**Comment by xupengkun** [comment]
@zhaofengnian18 @mrarronz

**Comment by mrarronz** [comment]
Xcode禁止了横屏，react-native-orientation肯定是无法转屏的。所以你必须把横屏和竖屏开关都打开，针对个别需要转屏的页面解锁屏幕旋转功能Orientation.unlockAllOrientations()，其它页面固定使用竖屏Orientation.lockToPortrait();

android中监听屏幕旋转不能用的话，你就需要手动点击视频缩放按钮调用Orientation.lockToPortrait();或者Orientation.lockToLandscape();。如果你当前是横屏，点击android的系统返回键，要回到竖屏，需要监听back键的点击事件。

**Comment by orzhtml** [comment]
每个需要竖屏的页面都要设置 Orientation.lockToPortrait() ？？？

**Comment by mrarronz** [comment]
@orzhtml 不需要每个页面去写Orientation.lockToPortrait()，在首页didMount函数中写一个就行了。如果在某个页面转屏显示横屏，退出这个页面的时候记得调用一下Orientation.lockToPortrait()。否则其它页面会受到影响
