### ISSUE TITLE
你有试过在FlatList中全屏吗?

### ISSUE THREAD

**Issue by shaoting0730** [mrarronz/react-native-blog-examples#3]
你有试过在FlatList中全屏吗?我试了无效啊.

**Comment by shaoting0730** [comment]
http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400  还有部分视频源该库是不是无法播放?

**Comment by mrarronz** [comment]
@pheromone 你为什么要在FlatList进行全屏呢？另外你发的这个地址在播放器上是加载不了吗？这个video组件可能只支持明文的视频后缀名，如.mp4、.mov之类的，建议你去官方[github repo](https://github.com/react-native-community/react-native-video/)下面提一个issue。

**Comment by shaoting0730** [comment]
@mrarronz  因为我们的需求是这样的.在FlatList中有很多视频,每个视频理应可以全屏.这个问题我暂时无法解决.只能先隐藏全屏按钮.只是视频后缀名的这个问题,我采用https://github.com/abbasfreestyle/react-native-af-video-player这个库是可以播放的,并且作者也正在解决长列表的全屏问题.该库也是基于react-native-video而来的,可能他做了什么处理吧.

**Comment by mrarronz** [comment]
react-native-af-video-player也是基于react-native-video的。作者也说了`Also having multiple videos in a ScrollView isn't perfect`。如果你想实现一个列表，每个row中都渲染一个video组件是不太好的做法，这肯定会影响性能。RN中组件的使用方式是比较死板的，没有原生端灵活，像这种页面建议还是原生实现更好。如果要做的话，我建议为了性能考虑，列表页的的视频用封面图片代替显示，点击视频跳到一个公共页面进行播放。
