### ISSUE TITLE
无法扫描matrix code

### ISSUE THREAD

**Issue by yantaosh** [mrarronz/react-native-blog-examples#37]
项目中有这样的需求,但是我们要扫描的是一个matrix code,发现对这个不支持

**Comment by mrarronz** [comment]
demo只支持qr二维码扫描，没有做对Data Matrix码的支持。

如果你用react-native-camera这个库的话也是支持的，只需要将`RNCamera`组件的属性`barCodeTypes`改为：

```
barCodeTypes={[RNCamera.Constants.BarCodeType.qr, RNCamera.Constants.BarCodeType.datamatrix]}
```
即可。

如果想使用原生代码自己实现，iOS原生AVFoundation框架和google zxing扫码库都是支持的。
