### ISSUE TITLE
react-native-video 安卓重播只有声音没有画面

### ISSUE THREAD

**Issue by chenzhenbo** [mrarronz/react-native-blog-examples#4]
react-native-video 版本 3.2.0
机型：小米6 
单视频播放结束后，重新播放会出现只有声音，没有画面

**Comment by mrarronz** [comment]
我用华为荣耀千元机测试了一下VideoExample这个demo，react-native-video版本改为3.2.0，重新安装后运行，重播功能正常。我手上没有小米6，无法重现你说的问题，你的视频url是多少？现在问题解决了吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by chenzhenbo** [comment]
换了视频源就可以，你demo中的视频源就会有问题
