### ISSUE TITLE
Chapter3-SectionList/SectionListExample里那个"即将上映"标题不能悬浮

### ISSUE THREAD

**Issue by jiangli1984** [mrarronz/react-native-blog-examples#6]
新手请教,在android5.1上,(没有其他版本...)
当把列表上拉,超过即将上映的电影后,"即将上映"标题不能悬浮.不知道是不是android版本的问题..

**Comment by jiangli1984** [comment]
刚刚试了7.0版本也不行.不知道什么原因了.
直接用的例子运行,未做任何修改.

**Comment by mrarronz** [comment]
标题悬浮功能是iOS系统独有的特性，android默认是没有的，这与SectionList组件在iOS和android各自平台的具体实现有关，iOS系统UITableView能够支持分组标题吸顶悬浮，android的ListView是不支持的，需要自己实现。
