### ISSUE TITLE
『RN中集成原生端二维码扫描功能』，请问有考虑封装一个组件库吗

### ISSUE THREAD

**Issue by GreatAuk** [mrarronz/react-native-blog-examples#8]

**Comment by mrarronz** [comment]
最近暂时没有这方面计划，你可以自己试试。

iOS组件可以用我的仓库[QRCodeScanner](https://github.com/mrarronz/QRCodeScanner)，使用比较简单。android推荐使用谷歌的zxing库，android端原生实现也可以参考[zxing](https://github.com/yuzhiqiang1993/zxing)。

我的想法是：先基于iOS和android原生实现扫码组件，然后做RN的封装，这样做起来思路更清晰，两端功能可以尽量统一。
